# basic options, i can say whatever. it's a comment line
title: Personal Website
author: Risvan Dirza
email: risvan.dirza@gmail.com
description: Personal Website
# twitter_username: jekyllrb
github_username: RisvanDirza

# Build settings
markdown: kramdown
theme: minima
